
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PulSalud</title>
<style>

/* CSS goes here. */
svg{
    font-family: sans-serif;
}
footer{
  position: fixed;
  bottom: 0px;
  text-align: center;
  background: black;
  color: white;
  width:100%;
}
.selected{
  opacity: 1;
}
#details{
  position: fixed;
  top: 72px;
  right:0px;

}

.bar{
}
.comuna{
  stroke-width: 0.1px;
  stroke: #000;
}

.title{
  font-family: Helvetica Neue;
  font-weight: 300;
  font-size: 200%;
}
.chart1-text{
  font-size: 10px;
  color: "white";
}
.tooltip{
  font-size: 10px;
  color: "white";
}
.sparkline {
  fill: none;
  stroke: #000;
  stroke-width:   5px;
}
.sparkcircle {
  fill: #f00;
  stroke: none;
}
</style>
    <!-- Bootstrap CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/bootstrapValidator.min.css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
