<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Pul<span style="color:LimeGreen">Salud</span></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/home">Home</a></li>
      <li><a href="/diabetes">Diabetes</a></li>
      <li><a href="/hipertension">Hipertensión</a></li>
      <li><a href="/compara">Comparación de comunas</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><button data-toggle="modal" class="btn btn-sm" data-target="#myModal">Recibe alertas de nuevas actualizaciones</button></li>
      </ul>
  </div><!-- /.navbar-collapse -->
</nav>



    <!-- jQuery -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/bootstrapValidator.min.js"></script>